spring:
  application:
    name: nartyBackend
  datasource:
    url: jdbc:mysql://localhost:3306/slonecznaDolinaBackend?createDatabaseIfNotExist=true
    username: root
    password: qwerty
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenValiditySeconds: 900
    refreshTokenValiditySeconds: 604800